### ISSUE TITLE
VIRSorter_global-phage-signal.csv has no content

### ISSUE THREAD

**Issue by 473021677** [simroux/VirSorter#30]
When I was running VirSorter, it didn't report any error. But when the program finished, one result file, namely VIRSorter_global-phage-signal.csv hadn't any content. Can someone help me?

**Comment by jarrodscott** [comment]
Hi @473021677  

I may be having a similar problem (see the later parts of this issue thread [https://github.com/simroux/VirSorter/issues/28)](url)


It seems like the issue can be traced back to `Step_3`. As suggested by the developers I ran 
`/path/to/Virsorter/Scripts/Step_3_highlight_phage_signal.pl Metric_files/VIRSorter_affi-contigs.tab VIRSorter_phage_signal_test.csv 16`

And got back a blank file. I am curious how you installed `Virsorter` because I suspect there is something wrong with my installation. I followed the recipe for the `conda` install

[/path/to/Virsorter/Scripts/Step_3_highlight_phage_signal.pl Metric_files/VIRSorter_affi-contigs.tab VIRSorter_phage_signal_test.csv 16](url)

**Comment by 473021677** [comment]
Hi jarrodscott:
Yes. I am sure that there must be soemthing wrong with the installation because many dependency packages have been needed during the installation. I cann't solve the problem. So I have decided to use VirSorter in the iPlant discovery environment(https://de.iplantcollaborative.org/de/). And I have used the app to predict the viral genomes and prophages from my metagenomic datasets successfully.  

Best,
Yuan

**Comment by jarrodscott** [comment]
@473021677 
Hi Yuan
 I was unable to solve the problem as well so I took your advice and have the datasets running on iPlant! Thanks for your help!

Best, 
Jarrod

**Comment by 473021677** [comment]
Hi Jarrod
   It's my pleasure to help you.


Best,
Yuan
 
 
------------------ Original ------------------

**Comment by simroux** [comment]
Hi Yuan and Jarrod,

I believe that in both your cases, the issue you had was with the C script used to calculate enrichment statistics. This should now be fixed, plus we have a new option ("--no_c") to tell VirSorter to not use this C script and instead use a perl alternative, which is slower but should work on most systems. 

If you have the occasion, please re-install VirSorter the same way as you did before (i.e. follow the conda environment guide in the readme), and let me know if this solve your problems !

**Comment by istmobiome** [comment]
Hi Simon, 

I reinstalled VirSorter (using the updated `conda` recipe) and ran the test fasta file you (or Bryan) sent. Looks like it worked great! I am attaching the `err`, `log`, and `VIRSorter_global-phage-signal.csv` files so you can have a look [test_out.zip](https://github.com/simroux/VirSorter/files/2088180/test_out.zip).  Let me know if anything looks funny. 

If all looks good this can close my original issue which started off as a `Diamond` version problem [#28](https://github.com/simroux/VirSorter/issues/28)

Thanks to you and Bryan for all the help and an awesome program.

**Comment by istmobiome** [comment]
oops, here is the command I ran

`wrapper_phage_contigs_sorter_iPlant.pl -f input_sequences.fna --ncpu 20 --db 2 --wdir test_master --data-dir ~/virsorter-data --diamond` and it looks like the default for `--no_c` is `0`. So it ran fine with the C script?

**Comment by simroux** [comment]
Hi Jarrod, 

Yes, the default is still to use the C script, it has been updated so that it should now compile and run on more modern gcc, so I was hopeful your problem would have been fixed (and it seems like it was !). The "no_c" option has been added mostly to avoid future cases like this, i.e. if in the future there is a new issue with the C script, users will be able to use "no_c" to get a VirSorter result.

**Comment by Sapsanas** [comment]
Hi Simon, 

I am very sorry for bothering you again, but as I see, this update should have solved the issue that I faced as well https://github.com/simroux/VirSorter/issues/29 
However, after reinstalling VirSorter using conda and specifying the option --no_c, I still do not get any results. Could you please help me with? 

[VirSorter_Sapsanas.zip](https://github.com/simroux/VirSorter/files/2094873/VirSorter_Sapsanas.zip)


Thank you in advance.

**Comment by Sapsanas** [comment]
Dear Simon,

I rerun VirSorter on this sample, please find attached the output. 
[VirSorter_Sapsanas_new.zip](https://github.com/simroux/VirSorter/files/2103349/VirSorter_Sapsanas_new.zip)

**Comment by simroux** [comment]
Hi,

It looks like metagene_annotator was not installed, so VirSorter could not predict proteins. Could you double check on the README that you followed the specific step after "Finally, you'll need to download MetaGeneAnnotator ... " ?

**Comment by thierryjanssens** [comment]
Dear Simon,

I experience the same problem, i.e. an empty final csv file, despite the prediction o significant prophages by other packages.
 mga_linux_ia64 has been installed in the env bin folder. Also the option --no_c does not relieve this problem.
I am looking forward for your help.

Kind regards,

Thierry

**Comment by simroux** [comment]
Dear Thierry,

Could you send the log files of the VirSorter run ? There are (unfortunately) a number of reasons why the final csv would be empty, but hopefully we can figure what's going on there.

Thanks,
Best,
Simon

**Comment by thierryjanssens** [comment]
Hello Simon,

have you received the log files in the email of 2 days ago?

Regards,

Thierry

**Comment by simroux** [comment]
Hi Thierry,

Sorry, I didn't receive any email. You can attach them to your messages here, or send them to sroux (at) lbl.gov
